# Generated by Django 4.1.3 on 2022-12-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=128)),
                ('disciption', models.CharField(max_length=128)),
                ('money', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=8)),
            ],
        ),
    ]
