# Generated by Django 4.1.3 on 2022-12-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepAccount', '0002_alter_account_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(),
        ),
    ]
