# Generated by Django 4.1.3 on 2022-12-23 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keepAccount', '0003_alter_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='userName',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='disciption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('1', '食'), ('2', '衣'), ('3', '住'), ('4', '行'), ('5', '育'), ('6', '樂')], default='1', max_length=20),
        ),
    ]
