# Generated by Django 4.1.3 on 2022-12-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepAccount', '0005_rename_money_account_cost_alter_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='disciption',
            new_name='desciption',
        ),
    ]
