# Generated by Django 4.1.3 on 2022-12-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepAccount', '0006_rename_disciption_account_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='desciption',
            new_name='description',
        ),
    ]
