# Generated by Django 4.1.3 on 2022-12-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepAccount', '0007_rename_desciption_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(default='26.12.2022 02:05:39'),
        ),
    ]
