# Generated by Django 4.1.3 on 2022-12-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepAccount', '0012_alter_account_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('食', '食'), ('衣', '衣'), ('住', '住'), ('行', '行'), ('育', '育'), ('樂', '樂'), ('其他', '其他')], default='1', max_length=20),
        ),
    ]
