# Generated by Django 4.1.3 on 2022-12-28 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keepAccount', '0013_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('食', '食'), ('衣', '衣'), ('住', '住'), ('行', '行'), ('育', '育'), ('樂', '樂'), ('收入', '收入'), ('其他', '其他')], default='1', max_length=20),
        ),
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.IntegerField(blank=True)),
                ('expectedCost', models.IntegerField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
